defaults: &defaults
  working_directory: ~/project
  docker: [ image: 'nfour/circleci-node:9' ]

defaultSteps: &restoreCache
  restore_cache:
    keys:
    - deps-{{ checksum "package.json" }}
    - deps-

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: yarn install
      - save_cache:
          paths: [node_modules, build]
          key: deps-{{ checksum "package.json" }}

  lintTest:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: yarn lint

  unitTest:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: yarn test:coverage

  changelogTest:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: yarn changelog:verify

  deploy:
    <<: *defaults

    steps:
      - checkout
      - *restoreCache
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn release

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - lintTest: { requires: [build] }
      - unitTest: { requires: [build] }
      - changelogTest: { requires: [build] }
      - deploy:
          requires: [build, lintTest, unitTest, changelogTest]
          filters:
            tags: { only: /^v.*/ }
            branches: { ignore: /.*/ }

